[package]
name = "audio_decoder_wasm"
edition = "2021"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
symphonia = { version = "0.5.4", features = ["mp3"] }